// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKLfc6sbLgeZotODZGqY0XCbOdM00uUu0',
    appId: '1:932084544401:web:e872fda22e49b88bfa2030',
    messagingSenderId: '932084544401',
    projectId: 'edu-ride',
    authDomain: 'edu-ride.firebaseapp.com',
    storageBucket: 'edu-ride.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLaVVUN_rjMc0G2mXDGD8sL7v-mrpsIA',
    appId: '1:932084544401:android:fc098c268bf04784fa2030',
    messagingSenderId: '932084544401',
    projectId: 'edu-ride',
    storageBucket: 'edu-ride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgn35oYYLcDm3aaAA70r0QEaOm5yhqzgo',
    appId: '1:932084544401:ios:257be508f9ae1195fa2030',
    messagingSenderId: '932084544401',
    projectId: 'edu-ride',
    storageBucket: 'edu-ride.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgn35oYYLcDm3aaAA70r0QEaOm5yhqzgo',
    appId: '1:932084544401:ios:257be508f9ae1195fa2030',
    messagingSenderId: '932084544401',
    projectId: 'edu-ride',
    storageBucket: 'edu-ride.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKLfc6sbLgeZotODZGqY0XCbOdM00uUu0',
    appId: '1:932084544401:web:460dd2dba11a4eadfa2030',
    messagingSenderId: '932084544401',
    projectId: 'edu-ride',
    authDomain: 'edu-ride.firebaseapp.com',
    storageBucket: 'edu-ride.appspot.com',
  );

}